version: '3.9'

services:
  db:
    container_name: pg_db
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: storage
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.29-management
    volumes:
      - ./data/rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    ports:
      - "5672:5672"
      - "15672:15672"