--liquibase formatted sql
--changeset danik-dev:1
--comment initial database schema
CREATE TABLE "app_document" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "doc_name" VARCHAR(255),
    "file_size" BIGINT,
    "mime_type" VARCHAR(255),
    "telegram_file_id" VARCHAR(255),
    "binary_content_id" BIGINT,
    CONSTRAINT "app_document_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "app_photo" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "file_size" INTEGER,
    "telegram_file_id" VARCHAR(255),
    "binary_content_id" BIGINT,
    CONSTRAINT "app_photo_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "app_user" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) NOT NULL,
    "email" VARCHAR(255),
    "first_login_date" TIMESTAMP WITHOUT TIME ZONE,
    "first_name" VARCHAR(255),
    "is_active" BOOLEAN,
    "last_name" VARCHAR(255),
    "state" VARCHAR(255),
    "telegram_user_id" BIGINT,
    "username" VARCHAR(255),
    CONSTRAINT "app_user_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "binary_content" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "file_as_array_of_bytes" BYTEA,
    CONSTRAINT "binary_content_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "raw_data" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) NOT NULL,
    "event" JSONB,
    CONSTRAINT "raw_data_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "app_document"
ADD CONSTRAINT "uk_s9nc7867rk4c59viw2i95edru" UNIQUE ("binary_content_id");
ALTER TABLE "app_photo"
ADD CONSTRAINT "uk_gv3m3ecpombbd2cme9shucohr" UNIQUE ("binary_content_id");
ALTER TABLE "app_document"
ADD CONSTRAINT "fkfcm2si6jix496diei6g94rrxm" FOREIGN KEY ("binary_content_id") REFERENCES "binary_content" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "app_photo"
ADD CONSTRAINT "fksrw4o8i2rpx21b5wsu5yts4uu" FOREIGN KEY ("binary_content_id") REFERENCES "binary_content" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
--rollback truncate TABLE "app_document"; truncate TABLE "app_photo"; truncate TABLE "app_user"; truncate TABLE "binary_content"; truncate TABLE "raw_data";